### ISSUE TITLE
Spotify Label

### ISSUE THREAD

**Issue by Paralusion** [koolskateguy89/gnome-shell-extension-spotify-controller#1]
I'd like to replicate the same Spotify label you have in your README

**Comment by koolskateguy89** [comment]
Here's what I did:

- Added showing album (as an option - default false) (the max length is half the max length of the other fields - you can change this in `extension.js`)
- Added removing features from song title (as an option - default false)
- Added the Spotify icon on the left of the label
- Added Unicode brackets around the label (U+2770 & U+2771)

Here's a [zip file](https://github.com/koolskateguy89/gnome-shell-extension-spotify-controller/files/6025943/modifiedSpotifyLabel.zip) of the extensions with my modifications.

Unzip it into `~/.local/share/gnome=shell/extensions/` (for as a clean as possible installation, move your current `gnomespotifylabel@mheine.github.com` folder to somewhere else so you always have a backup if something breaks or you want to go back, then unzip to the extensions directory)

`unzip modifiedSpotifyLabel.zip -d ~/.local/share/gnome=shell/extensions/`

**NOTE: if you update the extension, the changes will be lost (I think)**
