### ISSUE TITLE
Like Icon

### ISSUE THREAD

**Issue by Boffice** [koolskateguy89/gnome-shell-extension-spotify-controller#16]
Would be amazing if you could support like button.

**Comment by koolskateguy89** [comment]
I've looked into this and it's not going to be simple to implement as I'd have to use the Spotify web API:

- [Implement authorization](https://developer.spotify.com/documentation/general/guides/authorization/code-flow/)
- [Save track for current user](https://developer.spotify.com/console/put-current-user-saved-tracks/) using metadata from MPRIS

I don't have the time to do this right now, maybe towards the end of July.
