### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by drzel** [koolskateguy89/gnome-shell-extension-spotify-controller#2]
When enabled it seems to cause my system to lag every 2 seconds, causing stuttering in videos etc.

**Comment by koolskateguy89** [comment]
I had this issue as well and had an idea what was causing it but after more investigation I found the [culprit](https://github.com/koolskateguy89/gnome-shell-extension-spotify-controller/blob/86bbedce4e7a1fe32fc808b76c12b47071d645ef/spotify-controller%40koolskateguy89/extension.js#L300).

For some reason when using a timeout less than 1 second, it seems to just refresh as many times as it can - in my case ~20 times a second. I'm gonna change it to 1 second & commit but I'm working on another potential performance improvement atm, once that's done I'll push & reupload to Gnome Extensions

**Comment by koolskateguy89** [comment]
@drzel it should be fixed now, I've submitted it to the GNOME Extensions website - waiting for review. If you uninstall the extension then manually install it through the instructions in the README, it should be fixed.
