### ISSUE TITLE
Newer GNOME version dosnt work

### ISSUE THREAD

**Issue by DerDennisOP** [koolskateguy89/gnome-shell-extension-spotify-controller#23]
Thanks!

**Comment by koolskateguy89** [comment]
What do you mean?

**Comment by DerDennisOP** [comment]
The extension is incompatible for newer gnoe versions

**Comment by koolskateguy89** [comment]
Can you give more details? Which versions? What error(s) are you getting?

**Comment by j-80** [comment]
On my Gnome 42.5 its only media buttons like pause, play, next and previous. No name of song

**Comment by koolskateguy89** [comment]
@djurk41 Please read the README, the song name comes from a different extension

**Comment by DerDennisOP** [comment]
It seams to be fixed by now already
