### ISSUE TITLE
Gnome 40

### ISSUE THREAD

**Issue by caiohsilveira** [koolskateguy89/gnome-shell-extension-spotify-controller#9]
The extension does not work with gnome 40.4.0
I was using it on pop! 21.04, but after upgrading to 21.10 it doesn't work anymore.

Here is the problem:

Error: No property border_width on GtkBox

Stack trace:
  _init/Gtk.Widget.prototype._init@resource:///org/gnome/gjs/modules/core/overrides/Gtk.js:45:40
  buildPrefsWidget@/home/user/.local/share/gnome-shell/extensions/spotify-controller@koolskateguy89/prefs.js:42:15
  _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:209:40
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
  run@resource:///org/gnome/gjs/modules/script/package.js:206:19
  start@resource:///org/gnome/gjs/modules/script/package.js:190:8
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17

**Comment by koolskateguy89** [comment]
I'll begin working on this in the next week

**Comment by koolskateguy89** [comment]
(didnt mean to close)

**Comment by koolskateguy89** [comment]
Small update, nearly done, should be done by tomorrow evening.

**Comment by koolskateguy89** [comment]
Another update: basically done but there's a bug with customising icon colours (`Gdk.RGBA#parse` takes `string` not `String`)

**Comment by koolskateguy89** [comment]
Done! It's completely working for me, waiting for it to be approved on EGO. Let me know if you have any problems.
